# Define the goal
float32[] j_arrays # Joint space target written as array of 6 floats
float32[] l_arrays # Cartesian space target written as array of 6 floats
sensor_msgs/JointState j_joints # Joint space target written as JointState (position,velocity,effort)
geometry_msgs/Pose[] poses
float32[] speeds # Speed parameter as in the urscript documentation for 'movej' command.
float32[] accs # Speed parameter as in the urscript documentation for 'movej' command.
float32[] blends # Blend radius parameter as in the urscript documentation for 'movej' command.
bool forced # This flag stops the current running program on the UR and forces the start of this motion.
string[] targets # Flag for seting MoveJ movement. MoveL will be used if not set.
float32[] offsets # Pose offsets written as array of 6 or 7 floats
geometry_msgs/Pose[] wobjs # Work object for offsets in work object orientation
geometry_msgs/Pose[] f_poses # Pose that defines a task frame for force mode
int8[] f_vectors # Array that determines axes of compliance in task frame: 1 - compliant, 0 - non compliant, [x,y,z,rx,ry,rz]
float32[] f_wrenches # Array that determines forces that will be applied in axes of task frame: units - N, [x,y,z,rx,ry,rz]
int8[] f_types # An integer [1;3] specifying how the robot interprets the force frame.
               # 1: The force frame is transformed in a way such that its y-axis is aligned with
               # a vector pointing from the robot tcp towards the origin of the force frame.
               # 2: The force frame is not transformed.
               # 3: The force frame is transformed in a way such that its x-axis is the projection
               # of the robot tcp velocity vector onto the x-y plane of the force frame.
float32[] f_limits # Array that determines tcp speed limits for compliant axes and 
                   # maximum travel distance for non compliant axes[x,y,z,rx,ry,rz]
---
# Define the result
float32 execution_time
float32 joint_norm_err
float32 pose_norm_err
geometry_msgs/Pose pose_err
sensor_msgs/JointState joint_err
---
# Define a feedback message
float32 execution_time
float32 joint_norm_err
float32 pose_norm_err
geometry_msgs/Pose pose_err
sensor_msgs/JointState joint_err
#############################################